version: '3.9'
services:
  gateway:
    build:
      context: ./
      dockerfile: ./apps/gateway/dockerfile
    env_file:
      - .env
    command:
      - npm
      - run
      - start:dev
      - gateway
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    depends_on:
      - rabbitmq

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/dockerfile
    env_file:
      - .env
    command:
      - npm
      - run
      - start:dev
      - auth
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    depends_on:
      - rabbitmq
      - gateway

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672' # Management UI
      - '5672:5672' # Default RabbitMQ Port

volumes:
  nodemodules: {}
