version: '3.9'
services:
  # gateway:
  #   # image: gateway
  #   build:
  #     context: gateway
  #   command:
  #     - npm
  #     - run
  #     - start:dev
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./gateway:/app
  #     - nodemodules_gateway:/app/node_modules
  #   depends_on:
  #     - rabbitmq

  # auth:
  #   # image: auth
  #   build: microservices/auth
  #   command: npm run start:dev
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./microservices/auth:/app
  #     - nodemodules_auth:/app/node_modules
  #   depends_on:
  #     - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672' # Management UI
      - '5672:5672' # Default RabbitMQ Port

# volumes:
#   nodemodules_gateway: {}
#   nodemodules_auth: {}
